[package]
name = "alpha-stamp"
version = "0.1.0"
description = "A simple SOL vault program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "alpha_stamp"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = "0.32.1"
blake3 = "=1.5.5"
sha2 = "0.10"

[dev-dependencies]
litesvm = "=0.7.1"
solana-sdk = "2.3"
